# https://docs.github.com/en/actions/learn-github-actions/contexts
# https://docs.github.com/en/rest/overview/github-event-types
name: Benchmark
on:
  push:
    branches:
      - master
permissions:
  contents: write
  pages: write
  deployments: write

jobs:
  benchmark:
    name: Performance regression check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Run benchmark
        run: ./gradlew jmh

      # Run `github-action-benchmark` action
      - name: Compare benchmark results
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: 'jmh'
          # Where the output from the benchmark tool is stored
          output-file-path: ./jemoji/build/results/jmh/results.json
          # Where the previous data file is stored
          #external-data-json-path: ./cache/benchmark-data.json
          gh-repository: github.com/felldo/JEmoji
          # Workflow will fail when an alert happens
          fail-on-alert: false
          alert-threshold: 200%
          # GitHub API token to make a commit comment
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Enable alert commit comment
          comment-on-alert: true
          save-data-file: false

      # Publish only on master branch
      - name: Publish benchmark result to GH Pages
        if: ${{ github.repository == 'felldo/JEmoji' && github.ref_name == 'master' }}
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: 'jmh'
          # Where the output from the benchmark tool is stored
          output-file-path: ./jemoji/build/results/jmh/results.json
          # Workflow will fail when an alert happens
          fail-on-alert: false
          alert-threshold: 125%
          # GitHub API token to make a commit comment
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Enable alert commit comment
          comment-on-alert: true
          # Mention user in the commit comment
          alert-comment-cc-users: '@felldo'
          auto-push: true
