name: Benchmark and deploy
on:
  push:
    branches:
      - master

permissions:
  contents: write
  pages: write

jobs:
  benchmark:
    name: Performance regression check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Run benchmark
        run: ./gradlew jmh
      # Download previous benchmark result from cache (if exists)
      - name: Download previous benchmark data
        uses: actions/cache@v3
        with:
          path: ./cache/benchmark-data.json
          key: ${{ runner.os }}-benchmark
      # Run `github-action-benchmark` action
      - name: Save and Deploy benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: 'jmh'
          output-file-path: ./lib/build/results/jmh/results.json
          fail-on-alert: false
          alert-threshold: 1%
          github-token: ${{ secrets.GITHUB_TOKEN }}
          comment-on-alert: true
          summary-always: true
          alert-comment-cc-users: '@felldo'
          auto-push: true
      # Upload the updated cache file for the next job by actions/cache
      - name: Save benchmark JSON
        uses: actions/cache/save@v3
        with:
          path: ./cache/benchmark-data.json
          key: ${{ runner.os }}-benchmark
